name: Python PEP 8 Style Check

on:
  push:
    branches:
      - main

jobs:
  pycodestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Run pycodestyle
        run: |
          pycodestyle .